module.exports = {
  apps: [
    {
      name: 'ankaa-api-production-dev',
      script: 'src/main.ts',
      cwd: '/home/kennedy/ankaa/apps/api',
      interpreter: '/home/kennedy/ankaa/node_modules/.bin/ts-node-dev',
      interpreter_args: '--respawn --transpile-only -r tsconfig-paths/register',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3030,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3030,
      },
      error_file: '/var/log/ankaa/api-dev-production-error.log',
      out_file: '/var/log/ankaa/api-dev-production-out.log',
      log_file: '/var/log/ankaa/api-dev-production-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'ankaa-api-test-dev',
      script: 'src/main.ts',
      cwd: '/home/kennedy/ankaa/apps/api',
      interpreter: '/home/kennedy/ankaa/node_modules/.bin/ts-node-dev',
      interpreter_args: '--respawn --transpile-only -r tsconfig-paths/register',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'test',
        PORT: 3031,
      },
      env_test: {
        NODE_ENV: 'test',
        PORT: 3031,
      },
      error_file: '/var/log/ankaa/api-dev-test-error.log',
      out_file: '/var/log/ankaa/api-dev-test-out.log',
      log_file: '/var/log/ankaa/api-dev-test-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};
