-- Rename reembolso to reimbursement across all many-to-many relation tables
-- This migration renames all "reembolso" and "nfeReembolso" relation tables to use "reimbursement" naming

-- 1. AIRBRUSHING REIMBURSEMENTS
-- Rename _AIRBRUSHING_REEMBOLSOS to _AIRBRUSHING_REIMBURSEMENTS
ALTER TABLE "_AIRBRUSHING_REEMBOLSOS" RENAME TO "_AIRBRUSHING_REIMBURSEMENTS";

-- Rename _AIRBRUSHING_NFE_REEMBOLSOS to _AIRBRUSHING_NFE_REIMBURSEMENTS
ALTER TABLE "_AIRBRUSHING_NFE_REEMBOLSOS" RENAME TO "_AIRBRUSHING_NFE_REIMBURSEMENTS";

-- 2. EXTERNAL WITHDRAWAL REIMBURSEMENTS
-- Rename _EXTERNAL_WITHDRAWAL_REEMBOLSOS to _EXTERNAL_WITHDRAWAL_REIMBURSEMENTS
ALTER TABLE "_EXTERNAL_WITHDRAWAL_REEMBOLSOS" RENAME TO "_EXTERNAL_WITHDRAWAL_REIMBURSEMENTS";

-- Rename _EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS to _EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS" RENAME TO "_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS";

-- 3. ORDER REIMBURSEMENTS
-- Rename _ORDER_REEMBOLSOS to _ORDER_REIMBURSEMENTS
ALTER TABLE "_ORDER_REEMBOLSOS" RENAME TO "_ORDER_REIMBURSEMENTS";

-- Rename _ORDER_NFE_REEMBOLSOS to _ORDER_NFE_REIMBURSEMENTS
ALTER TABLE "_ORDER_NFE_REEMBOLSOS" RENAME TO "_ORDER_NFE_REIMBURSEMENTS";

-- 4. TASK REIMBURSEMENTS
-- Rename _TASK_REEMBOLSOS to _TASK_REIMBURSEMENTS
ALTER TABLE "_TASK_REEMBOLSOS" RENAME TO "_TASK_REIMBURSEMENTS";

-- Rename _TASK_NFE_REEMBOLSOS to _TASK_NFE_REIMBURSEMENTS
ALTER TABLE "_TASK_NFE_REEMBOLSOS" RENAME TO "_TASK_NFE_REIMBURSEMENTS";
