-- Rename + cleanup migration (data-preserving; hand-authored — NOT generated by `migrate dev`).
-- Four independent changes, applied IN ORDER (they share names, so order matters):
--   R1) truck side-measurements  Layout        -> ImplementMeasure
--                                LayoutSection -> ImplementMeasureSection
--       (frees the name "Layout" / value 'LAYOUT' for R2)
--   R2) paint-file entity        Artwork       -> Layout   (ArtworkStatus -> LayoutStatus,
--                                _TaskArtworks -> _TaskLayouts)
--   C1) remove ActivityReason.BORROW  (existing rows remapped to MANUAL_ADJUSTMENT)
--   C2) remove BorrowStatus.OVERDUE   (existing rows remapped to ACTIVE)
-- All statements are RENAME / data-preserving. No table is dropped/recreated. Data-safe on
-- zero or many rows (the pre-remap UPDATEs no-op when empty).
-- KEEP (unchanged): ServiceOrderType.ARTWORK, ServiceOrderStatus.WAITING_ARTWORK.

-- =====================================================================================
-- R1 — truck side-measurement models: Layout -> ImplementMeasure
-- =====================================================================================

-- ImplementMeasure (was Layout)
ALTER TABLE "Layout" RENAME TO "ImplementMeasure";
ALTER TABLE "ImplementMeasure" RENAME CONSTRAINT "Layout_pkey" TO "ImplementMeasure_pkey";
ALTER TABLE "ImplementMeasure" RENAME CONSTRAINT "Layout_photoId_fkey" TO "ImplementMeasure_photoId_fkey";

-- ImplementMeasureSection (was LayoutSection); FK column layoutId -> implementMeasureId
ALTER TABLE "LayoutSection" RENAME TO "ImplementMeasureSection";
ALTER TABLE "ImplementMeasureSection" RENAME COLUMN "layoutId" TO "implementMeasureId";
ALTER TABLE "ImplementMeasureSection" RENAME CONSTRAINT "LayoutSection_pkey" TO "ImplementMeasureSection_pkey";
ALTER TABLE "ImplementMeasureSection" RENAME CONSTRAINT "LayoutSection_layoutId_fkey" TO "ImplementMeasureSection_implementMeasureId_fkey";
ALTER INDEX "LayoutSection_layoutId_position_idx" RENAME TO "ImplementMeasureSection_implementMeasureId_position_idx";

-- Truck side-measure FK columns/constraints/indexes
ALTER TABLE "Truck" RENAME COLUMN "backSideLayoutId" TO "backSideMeasureId";
ALTER TABLE "Truck" RENAME COLUMN "leftSideLayoutId" TO "leftSideMeasureId";
ALTER TABLE "Truck" RENAME COLUMN "rightSideLayoutId" TO "rightSideMeasureId";
ALTER TABLE "Truck" RENAME CONSTRAINT "Truck_backSideLayoutId_fkey" TO "Truck_backSideMeasureId_fkey";
ALTER TABLE "Truck" RENAME CONSTRAINT "Truck_leftSideLayoutId_fkey" TO "Truck_leftSideMeasureId_fkey";
ALTER TABLE "Truck" RENAME CONSTRAINT "Truck_rightSideLayoutId_fkey" TO "Truck_rightSideMeasureId_fkey";
ALTER INDEX "Truck_backSideLayoutId_idx" RENAME TO "Truck_backSideMeasureId_idx";
ALTER INDEX "Truck_leftSideLayoutId_idx" RENAME TO "Truck_leftSideMeasureId_idx";
ALTER INDEX "Truck_rightSideLayoutId_idx" RENAME TO "Truck_rightSideMeasureId_idx";

-- ChangeLog entity enum value LAYOUT -> IMPLEMENT_MEASURE (existing rows follow the value)
ALTER TYPE "ChangeLogEntityType" RENAME VALUE 'LAYOUT' TO 'IMPLEMENT_MEASURE';

-- =====================================================================================
-- R2 — paint-file entity: Artwork -> Layout  (the name "Layout" is now free)
-- =====================================================================================

-- Layout (was Artwork)
ALTER TABLE "Artwork" RENAME TO "Layout";
ALTER TABLE "Layout" RENAME CONSTRAINT "Artwork_pkey" TO "Layout_pkey";
ALTER TABLE "Layout" RENAME CONSTRAINT "Artwork_airbrushingId_fkey" TO "Layout_airbrushingId_fkey";
ALTER TABLE "Layout" RENAME CONSTRAINT "Artwork_fileId_fkey" TO "Layout_fileId_fkey";
ALTER INDEX "Artwork_fileId_key" RENAME TO "Layout_fileId_key";
ALTER INDEX "Artwork_fileId_idx" RENAME TO "Layout_fileId_idx";
ALTER INDEX "Artwork_airbrushingId_idx" RENAME TO "Layout_airbrushingId_idx";
ALTER INDEX "Artwork_status_idx" RENAME TO "Layout_status_idx";

-- status enum ArtworkStatus -> LayoutStatus (values DRAFT/APPROVED/REPROVED unchanged)
ALTER TYPE "ArtworkStatus" RENAME TO "LayoutStatus";

-- implicit many-to-many join table _TaskArtworks -> _TaskLayouts
ALTER TABLE "_TaskArtworks" RENAME TO "_TaskLayouts";
ALTER TABLE "_TaskLayouts" RENAME CONSTRAINT "_TaskArtworks_AB_pkey" TO "_TaskLayouts_AB_pkey";
ALTER TABLE "_TaskLayouts" RENAME CONSTRAINT "_TaskArtworks_A_fkey" TO "_TaskLayouts_A_fkey";
ALTER TABLE "_TaskLayouts" RENAME CONSTRAINT "_TaskArtworks_B_fkey" TO "_TaskLayouts_B_fkey";
ALTER INDEX "_TaskArtworks_B_index" RENAME TO "_TaskLayouts_B_index";

-- =====================================================================================
-- C1 — remove ActivityReason.BORROW
-- Postgres cannot drop an in-use enum value, so remap rows first, then swap the type.
-- BORROW rows -> MANUAL_ADJUSTMENT (neutral, stays OUT of consumption stats like BORROW did).
-- reasonOrder 9 = ACTIVITY_REASON_ORDER[MANUAL_ADJUSTMENT].
-- =====================================================================================
UPDATE "Activity"
   SET "reason" = 'MANUAL_ADJUSTMENT', "reasonOrder" = 9
 WHERE "reason" = 'BORROW';

-- AlterEnum
BEGIN;
CREATE TYPE "ActivityReason_new" AS ENUM (
  'ORDER_RECEIVED', 'PRODUCTION_USAGE', 'PPE_DELIVERY', 'RETURN', 'EXTERNAL_OPERATION',
  'EXTERNAL_OPERATION_RETURN', 'INVENTORY_COUNT', 'MANUAL_ADJUSTMENT', 'MAINTENANCE',
  'DAMAGE', 'LOSS', 'PAINT_PRODUCTION', 'OTHER'
);
ALTER TABLE "Activity" ALTER COLUMN "reason" DROP DEFAULT;
ALTER TABLE "Activity" ALTER COLUMN "reason" TYPE "ActivityReason_new" USING ("reason"::text::"ActivityReason_new");
ALTER TYPE "ActivityReason" RENAME TO "ActivityReason_old";
ALTER TYPE "ActivityReason_new" RENAME TO "ActivityReason";
DROP TYPE "ActivityReason_old";
ALTER TABLE "Activity" ALTER COLUMN "reason" SET DEFAULT 'PRODUCTION_USAGE';
COMMIT;

-- =====================================================================================
-- C2 — remove BorrowStatus.OVERDUE
-- OVERDUE rows -> ACTIVE (an unreturned borrow is simply active). statusOrder 1 = ACTIVE.
-- =====================================================================================
UPDATE "Borrow"
   SET "status" = 'ACTIVE', "statusOrder" = 1
 WHERE "status" = 'OVERDUE';

-- AlterEnum
BEGIN;
CREATE TYPE "BorrowStatus_new" AS ENUM ('ACTIVE', 'RETURNED', 'LOST');
ALTER TABLE "Borrow" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Borrow" ALTER COLUMN "status" TYPE "BorrowStatus_new" USING ("status"::text::"BorrowStatus_new");
ALTER TYPE "BorrowStatus" RENAME TO "BorrowStatus_old";
ALTER TYPE "BorrowStatus_new" RENAME TO "BorrowStatus";
DROP TYPE "BorrowStatus_old";
ALTER TABLE "Borrow" ALTER COLUMN "status" SET DEFAULT 'ACTIVE';
COMMIT;
