-- CreateTable
CREATE TABLE "_TASK_BANK_SLIPS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_BANK_SLIPS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE INDEX "_TASK_BANK_SLIPS_B_index" ON "_TASK_BANK_SLIPS"("B");

-- AddForeignKey
ALTER TABLE "_TASK_BANK_SLIPS" ADD CONSTRAINT "_TASK_BANK_SLIPS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_BANK_SLIPS" ADD CONSTRAINT "_TASK_BANK_SLIPS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
