-- CreateTable (implicit many-to-many join table for ServiceOrder checkin files)
CREATE TABLE "_SERVICE_ORDER_CHECKIN_FILES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_SERVICE_ORDER_CHECKIN_FILES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_SERVICE_ORDER_CHECKIN_FILES_B_fkey" FOREIGN KEY ("B") REFERENCES "ServiceOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "_SERVICE_ORDER_CHECKIN_FILES_AB_unique" ON "_SERVICE_ORDER_CHECKIN_FILES"("A", "B");

-- CreateIndex
CREATE INDEX "_SERVICE_ORDER_CHECKIN_FILES_B_index" ON "_SERVICE_ORDER_CHECKIN_FILES"("B");

-- CreateTable (implicit many-to-many join table for ServiceOrder checkout files)
CREATE TABLE "_SERVICE_ORDER_CHECKOUT_FILES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_SERVICE_ORDER_CHECKOUT_FILES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_SERVICE_ORDER_CHECKOUT_FILES_B_fkey" FOREIGN KEY ("B") REFERENCES "ServiceOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "_SERVICE_ORDER_CHECKOUT_FILES_AB_unique" ON "_SERVICE_ORDER_CHECKOUT_FILES"("A", "B");

-- CreateIndex
CREATE INDEX "_SERVICE_ORDER_CHECKOUT_FILES_B_index" ON "_SERVICE_ORDER_CHECKOUT_FILES"("B");
