-- Update statusOrder for existing TaskQuote records to match new priority order:
-- DUE(1) → COMMERCIAL_APPROVED(2) → BUDGET_APPROVED(3) → BILLING_APPROVED(4) → UPCOMING(5) → PARTIAL(6) → SETTLED(7) → PENDING(8)
UPDATE "TaskQuote" SET "statusOrder" = CASE "status"
  WHEN 'DUE' THEN 1
  WHEN 'COMMERCIAL_APPROVED' THEN 2
  WHEN 'BUDGET_APPROVED' THEN 3
  WHEN 'BILLING_APPROVED' THEN 4
  WHEN 'UPCOMING' THEN 5
  WHEN 'PARTIAL' THEN 6
  WHEN 'SETTLED' THEN 7
  WHEN 'PENDING' THEN 8
  ELSE 1
END;
