-- Extends the GoalMetric enum with the additional metrics surfaced in the
-- statistics pages (production, HR, finance, order/inventory). Postgres
-- requires each new enum value to be added one at a time and outside any
-- containing transaction.

ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'TASKS_PER_ACTIVE_USER';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'PRODUCTION_AVG_PERFORMANCE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_HIRES_PER_MONTH';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_DISMISSALS_PER_MONTH';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_TURNOVER_RATE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_EXPERIENCE_FAILURE_RATE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_ABSENTEEISM_RATE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_PAYROLL_GROSS';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'HR_PAYROLL_BONUSES_TOTAL';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'FINANCE_DSO_DAYS';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'FINANCE_OVERDUE_AMOUNT';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'FINANCE_COLLECTION_RATE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'FINANCE_QUOTES_PER_PERIOD';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'FINANCE_CONVERSION_RATE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'ORDER_COUNT_PER_PERIOD';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'ORDER_TOTAL_VALUE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'INVENTORY_CONSUMPTION_VALUE';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'INVENTORY_OUTBOUND_VALUE';
