-- AlterTable
ALTER TABLE "_AIRBRUSHING_NFE_REIMBURSEMENTS" RENAME CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_AB_pkey" TO "_AIRBRUSHING_NFE_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_AIRBRUSHING_REIMBURSEMENTS" RENAME CONSTRAINT "_AIRBRUSHING_REEMBOLSOS_AB_pkey" TO "_AIRBRUSHING_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS" RENAME CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_AB_pkey" TO "_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_EXTERNAL_WITHDRAWAL_REIMBURSEMENTS" RENAME CONSTRAINT "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_AB_pkey" TO "_EXTERNAL_WITHDRAWAL_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_ORDER_NFE_REIMBURSEMENTS" RENAME CONSTRAINT "_ORDER_NFE_REEMBOLSOS_AB_pkey" TO "_ORDER_NFE_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_ORDER_REIMBURSEMENTS" RENAME CONSTRAINT "_ORDER_REEMBOLSOS_AB_pkey" TO "_ORDER_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_TASK_NFE_REIMBURSEMENTS" RENAME CONSTRAINT "_TASK_NFE_REEMBOLSOS_AB_pkey" TO "_TASK_NFE_REIMBURSEMENTS_AB_pkey";

-- AlterTable
ALTER TABLE "_TASK_REIMBURSEMENTS" RENAME CONSTRAINT "_TASK_REEMBOLSOS_AB_pkey" TO "_TASK_REIMBURSEMENTS_AB_pkey";

-- RenameIndex
ALTER INDEX "_AIRBRUSHING_NFE_REEMBOLSOS_B_index" RENAME TO "_AIRBRUSHING_NFE_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_AIRBRUSHING_REEMBOLSOS_B_index" RENAME TO "_AIRBRUSHING_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_B_index" RENAME TO "_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_B_index" RENAME TO "_EXTERNAL_WITHDRAWAL_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_ORDER_NFE_REEMBOLSOS_B_index" RENAME TO "_ORDER_NFE_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_ORDER_REEMBOLSOS_B_index" RENAME TO "_ORDER_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_TASK_NFE_REEMBOLSOS_B_index" RENAME TO "_TASK_NFE_REIMBURSEMENTS_B_index";

-- RenameIndex
ALTER INDEX "_TASK_REEMBOLSOS_B_index" RENAME TO "_TASK_REIMBURSEMENTS_B_index";
