/**
 * PAdES Signer Service (entity-agnostic)
 *
 * Applies a server-side PAdES seal to an arbitrary PDF buffer using the company
 * ICP-Brasil A1 certificate, optionally upgraded to **PAdES-B-T** by embedding an
 * RFC 3161 timestamp token from a trusted authority.
 *
 * Why B-T matters here and not for the HR flows: for an employee signing an EPI
 * receipt, a signing time taken from the company's own clock is defensible. For a
 * commercial counterparty in a dispute it is the first thing attacked — every
 * other piece of evidence in the dossier is generated by the interested party
 * (our server, our clock, our database). An independent TSA breaks that conflict
 * of interest, and defends against two distinct accusations at once: that the
 * *signer* backdated their act, and that *we* backdated our own database.
 *
 * Legal frame: MP 2.200-2/2001 art. 10 §2º (non-ICP means of proving authorship
 * and integrity) + DOC-ICP-15 AD-RT (≈ PAdES-B-T) when a credentialed ACT is used.
 *
 * Configuration (all optional — the service degrades instead of failing):
 *   SIGNATURE_CERT_PATH / SIGNATURE_CERT_PASSWORD   A1 .pfx (falls back to PPE_CERT_*)
 *   SIGNATURE_TSA_URL                               RFC 3161 endpoint; absent ⇒ B-B
 *   SIGNATURE_TSA_USER / SIGNATURE_TSA_PASSWORD     HTTP Basic (ICP-Brasil ACTs are authenticated)
 *   SIGNATURE_TSA_REQUIRED=true                     fail closed instead of degrading to B-B
 */

import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { existsSync, readFileSync } from 'fs';
import { resolve as resolvePath } from 'path';
import { plainAddPlaceholder } from '@signpdf/placeholder-plain';
import { SUBFILTER_ETSI_CADES_DETACHED } from '@signpdf/utils';
import signpdf from '@signpdf/signpdf';
import * as forge from 'node-forge';
import { CadesP12Signer } from './cades-p12-signer';
import { TsaClient } from './tsa-client';

export interface CertMetadata {
  subject: string;
  subjectCommonName: string;
  cnpj: string | null;
  issuer: string;
  serialNumber: string;
  notBefore: Date;
  notAfter: Date;
}

export type PadesLevel = 'B-B' | 'B-T';

export interface PadesSealResult {
  signedPdf: Buffer;
  cert: CertMetadata;
  sealedAt: Date;
  level: PadesLevel;
  /** TSA endpoint actually used, when a timestamp was embedded. */
  tsaUrl: string | null;
  /** TSA-asserted time (TSTInfo.genTime), when the token was parseable. */
  tsaGenTime: Date | null;
  /** Populated when a TSA was configured but no token could be embedded. */
  tsaError: string | null;
}

export interface PadesSealOptions {
  reason: string;
  location: string;
  signerName: string;
  contactInfo: string;
  signingTime?: Date;
}

/**
 * The signature placeholder is a fixed-size byte reservation. A B-T token carries
 * the TSA's full certificate chain and typically adds 4–8 KB, so the B-B budget is
 * not enough — undersizing produces a "signature exceeds placeholder" failure at
 * the very end of the pipeline.
 */
const PLACEHOLDER_BYTES_BB = 32768;
const PLACEHOLDER_BYTES_BT = 65536;

@Injectable()
export class PadesSignerService implements OnModuleInit {
  private readonly logger = new Logger(PadesSignerService.name);

  private p12Buffer: Buffer | null = null;
  private password: string | null = null;
  private certMeta: CertMetadata | null = null;

  private tsaClient: TsaClient | null = null;
  private tsaRequired = false;

  constructor(private readonly configService: ConfigService) {}

  onModuleInit(): void {
    this.loadCertificate();
    this.loadTsa();
  }

  isEnabled(): boolean {
    return this.p12Buffer !== null && this.password !== null && this.certMeta !== null;
  }

  getCertMetadata(): CertMetadata | null {
    return this.certMeta;
  }

  /** Whether a TSA is configured — i.e. whether seals will target B-T. */
  isTimestampEnabled(): boolean {
    return this.tsaClient !== null;
  }

  /** Days until the A1 expires; negative when already expired, null when unloaded. */
  getDaysToExpiry(): number | null {
    if (!this.certMeta) return null;
    return Math.floor((this.certMeta.notAfter.getTime() - Date.now()) / 86_400_000);
  }

  /**
   * Apply a single PAdES seal over `pdfBuffer`.
   *
   * This MUST be the last step of the pipeline. Everything that mutates page
   * content (visual seals, audit-trail pages, footers) has to happen before, or it
   * will invalidate the seal — the signed digest covers the whole file except the
   * /Contents hex string.
   */
  async sealPdf(pdfBuffer: Buffer, options: PadesSealOptions): Promise<PadesSealResult> {
    if (!this.isEnabled() || !this.p12Buffer || !this.password || !this.certMeta) {
      throw new Error('PAdES signer is not configured (missing certificate).');
    }

    const daysToExpiry = this.getDaysToExpiry();
    if (daysToExpiry !== null && daysToExpiry < 0) {
      throw new Error(
        `O certificado A1 expirou em ${this.certMeta.notAfter.toISOString()}. Renove antes de selar documentos.`,
      );
    }

    const sealedAt = options.signingTime ?? new Date();

    // plainAddPlaceholder appends the signature field as a proper PDF incremental
    // update (new XRef + trailer), preserving the original document revision. That
    // 2-revision structure is what strict PAdES validators expect.
    const pdfWithPlaceholder = plainAddPlaceholder({
      pdfBuffer,
      reason: options.reason,
      contactInfo: options.contactInfo,
      name: options.signerName,
      location: options.location,
      signingTime: sealedAt,
      subFilter: SUBFILTER_ETSI_CADES_DETACHED,
      signatureLength: this.tsaClient ? PLACEHOLDER_BYTES_BT : PLACEHOLDER_BYTES_BB,
    });

    const signer = new CadesP12Signer(this.p12Buffer, this.password, {
      tsaClient: this.tsaClient ?? undefined,
      tsaRequired: this.tsaRequired,
    });

    const signedPdf = await signpdf.sign(pdfWithPlaceholder, signer, sealedAt);

    const ts = signer.timestamp;
    const applied = ts?.applied === true;

    if (this.tsaClient && !applied) {
      // Not fatal unless SIGNATURE_TSA_REQUIRED — but it downgrades the evidentiary
      // level, so it must be visible rather than silent.
      this.logger.warn(
        `Selo aplicado sem carimbo do tempo (PAdES-B-B). Motivo: ${ts?.error ?? 'desconhecido'}`,
      );
    }

    return {
      signedPdf,
      cert: this.certMeta,
      sealedAt,
      level: applied ? 'B-T' : 'B-B',
      tsaUrl: applied ? this.tsaClient?.url ?? null : null,
      tsaGenTime: applied ? ts?.genTime ?? null : null,
      tsaError: this.tsaClient && !applied ? ts?.error ?? 'unknown' : null,
    };
  }

  // ---------------------------------------------------------------------------

  private loadCertificate(): void {
    // Falls back to the PPE variables so this works with the certificate already
    // configured today; split them once the cert is reissued off a secret store.
    const certPath =
      this.configService.get<string>('SIGNATURE_CERT_PATH') ??
      this.configService.get<string>('PPE_CERT_PATH');
    const certPassword =
      this.configService.get<string>('SIGNATURE_CERT_PASSWORD') ??
      this.configService.get<string>('PPE_CERT_PASSWORD');

    if (!certPath || !certPassword) {
      this.logger.warn(
        'Selo PAdES desabilitado — SIGNATURE_CERT_PATH/SIGNATURE_CERT_PASSWORD (ou PPE_CERT_*) não configurados.',
      );
      return;
    }

    const absolutePath = resolvePath(process.cwd(), certPath);
    if (!existsSync(absolutePath)) {
      this.logger.error(`Certificado não encontrado em ${absolutePath}`);
      return;
    }

    try {
      this.p12Buffer = readFileSync(absolutePath);
      this.password = certPassword;
      this.certMeta = this.parseCertMetadata(this.p12Buffer, certPassword);

      const days = this.getDaysToExpiry() ?? 0;
      this.logger.log(
        `Signer PAdES pronto — ${this.certMeta.subjectCommonName} (expira em ${days} dias)`,
      );
      if (days < 0) {
        this.logger.error('Certificado EXPIRADO — a selagem irá falhar.');
      } else if (days < 30) {
        this.logger.warn(`Certificado expira em ${days} dias — renove.`);
      }
    } catch (error) {
      this.logger.error(
        `Falha ao carregar o certificado: ${error instanceof Error ? error.message : error}`,
      );
      this.p12Buffer = null;
      this.password = null;
      this.certMeta = null;
    }
  }

  private loadTsa(): void {
    const url = this.configService.get<string>('SIGNATURE_TSA_URL');
    this.tsaRequired =
      String(this.configService.get<string>('SIGNATURE_TSA_REQUIRED') ?? '').toLowerCase() ===
      'true';

    if (!url) {
      this.logger.warn(
        'SIGNATURE_TSA_URL não configurada — os selos serão PAdES-B-B (hora do próprio servidor). ' +
          'Contrate uma ACT credenciada ICP-Brasil para atingir B-T/AD-RT.',
      );
      if (this.tsaRequired) {
        this.logger.error(
          'SIGNATURE_TSA_REQUIRED=true mas nenhuma SIGNATURE_TSA_URL foi definida — a selagem irá falhar.',
        );
      }
      return;
    }

    try {
      this.tsaClient = new TsaClient({
        url,
        username: this.configService.get<string>('SIGNATURE_TSA_USER') || undefined,
        password: this.configService.get<string>('SIGNATURE_TSA_PASSWORD') || undefined,
        timeoutMs: Number(this.configService.get<string>('SIGNATURE_TSA_TIMEOUT_MS') ?? 10_000),
      });
      this.logger.log(
        `Carimbo do tempo habilitado (${url})${this.tsaRequired ? ' — modo obrigatório' : ''}`,
      );
    } catch (error) {
      this.logger.error(
        `TSA inválida, seguindo em B-B: ${error instanceof Error ? error.message : error}`,
      );
      this.tsaClient = null;
    }
  }

  private parseCertMetadata(pfx: Buffer, password: string): CertMetadata {
    const p12Asn1 = forge.asn1.fromDer(pfx.toString('binary'));
    const p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, password);

    const certBags = p12.getBags({ bagType: forge.pki.oids.certBag });
    const bag = certBags[forge.pki.oids.certBag]?.[0];
    if (!bag || !bag.cert) {
      throw new Error('Certificado não encontrado dentro do PFX.');
    }

    const cert = bag.cert;
    const formatDn = (attrs: forge.pki.CertificateField[]): string =>
      attrs
        .map(a => `${a.shortName || a.name}=${a.value}`)
        .filter(Boolean)
        .join(', ');

    const cn = cert.subject.attributes.find(a => a.shortName === 'CN')?.value as
      | string
      | undefined;
    // ICP-Brasil CN convention is "RAZAO SOCIAL:CNPJ".
    const cnpjMatch = cn?.match(/:(\d{14})$/);

    return {
      subject: formatDn(cert.subject.attributes),
      subjectCommonName: cn || 'Unknown',
      cnpj: cnpjMatch ? cnpjMatch[1] : null,
      issuer: formatDn(cert.issuer.attributes),
      serialNumber: cert.serialNumber.toUpperCase(),
      notBefore: cert.validity.notBefore,
      notAfter: cert.validity.notAfter,
    };
  }
}
