/*
  Warnings:

  - The values [BUDGET] on the enum `ChangeLogEntityType` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `inscricaoEstadual` on the `Customer` table. All the data in the column will be lost.
  - You are about to drop the column `logradouroType` on the `Customer` table. All the data in the column will be lost.
  - You are about to drop the `_AIRBRUSHING_NFES` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_AIRBRUSHING_NFE_REIMBURSEMENTS` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_EXTERNAL_WITHDRAWAL_NFES` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_ORDER_NFES` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_ORDER_NFE_REIMBURSEMENTS` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_TASK_NFES` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `_TASK_NFE_REIMBURSEMENTS` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ChangeLogEntityType_new" AS ENUM ('ABSENCE', 'ACTIVITY', 'AIRBRUSHING', 'BORROW', 'CALCULATION', 'CALCULATION_DETAIL', 'CALCULATION_DECOMPOSITION', 'CATEGORY', 'COLLECTION', 'CUSTOMER', 'CUT', 'CUT_ITEM', 'CUT_PLAN', 'CUT_REQUEST', 'DELIVERY', 'PPE_DELIVERY', 'PPE_DELIVERY_ITEM', 'PPE_REQUEST', 'PPE_DELIVERY_SCHEDULE', 'PPE_SIZE', 'ECONOMIC_ACTIVITY', 'EXTERNAL_WITHDRAWAL', 'EXTERNAL_WITHDRAWAL_ITEM', 'FILE', 'ITEM', 'ITEM_BRAND', 'ITEM_CATEGORY', 'MAINTENANCE', 'MAINTENANCE_SCHEDULE', 'NOTIFICATION', 'ORDER', 'ORDER_ITEM', 'ORDER_RULE', 'ORDER_SCHEDULE', 'PAINT', 'PAINT_TYPE', 'SERVICE', 'PAINT_GROUND', 'PAINT_FORMULA', 'PAINT_FORMULA_COMPONENT', 'PAINT_PRODUCTION', 'PIECE', 'POSITION', 'PRODUCTION', 'PURCHASE', 'WARNING', 'SECTOR', 'SERVICE_ORDER', 'SUPPLIER', 'TASK', 'TRUCK', 'LAYOUT', 'USER', 'VACATION', 'DEPLOYMENT');
ALTER TABLE "ChangeLog" ALTER COLUMN "entityType" TYPE "ChangeLogEntityType_new" USING ("entityType"::text::"ChangeLogEntityType_new");
ALTER TYPE "ChangeLogEntityType" RENAME TO "ChangeLogEntityType_old";
ALTER TYPE "ChangeLogEntityType_new" RENAME TO "ChangeLogEntityType";
DROP TYPE "public"."ChangeLogEntityType_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "public"."_AIRBRUSHING_NFES" DROP CONSTRAINT "_AIRBRUSHING_NFES_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_AIRBRUSHING_NFES" DROP CONSTRAINT "_AIRBRUSHING_NFES_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_AIRBRUSHING_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_AIRBRUSHING_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_EXTERNAL_WITHDRAWAL_NFES" DROP CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFES_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_EXTERNAL_WITHDRAWAL_NFES" DROP CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFES_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_ORDER_NFES" DROP CONSTRAINT "_ORDER_NFES_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_ORDER_NFES" DROP CONSTRAINT "_ORDER_NFES_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_ORDER_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_ORDER_NFE_REEMBOLSOS_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_ORDER_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_ORDER_NFE_REEMBOLSOS_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_TASK_NFES" DROP CONSTRAINT "_TASK_NFES_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_TASK_NFES" DROP CONSTRAINT "_TASK_NFES_B_fkey";

-- DropForeignKey
ALTER TABLE "public"."_TASK_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_TASK_NFE_REEMBOLSOS_A_fkey";

-- DropForeignKey
ALTER TABLE "public"."_TASK_NFE_REIMBURSEMENTS" DROP CONSTRAINT "_TASK_NFE_REEMBOLSOS_B_fkey";

-- AlterTable
ALTER TABLE "Customer" DROP COLUMN "inscricaoEstadual",
DROP COLUMN "logradouroType";

-- AlterTable
ALTER TABLE "Paint" ADD COLUMN     "colorOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Supplier" ADD COLUMN     "logradouro" "LogradouroType";

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avatarId" TEXT;

-- DropTable
DROP TABLE "public"."_AIRBRUSHING_NFES";

-- DropTable
DROP TABLE "public"."_AIRBRUSHING_NFE_REIMBURSEMENTS";

-- DropTable
DROP TABLE "public"."_EXTERNAL_WITHDRAWAL_NFES";

-- DropTable
DROP TABLE "public"."_EXTERNAL_WITHDRAWAL_NFE_REIMBURSEMENTS";

-- DropTable
DROP TABLE "public"."_ORDER_NFES";

-- DropTable
DROP TABLE "public"."_ORDER_NFE_REIMBURSEMENTS";

-- DropTable
DROP TABLE "public"."_TASK_NFES";

-- DropTable
DROP TABLE "public"."_TASK_NFE_REIMBURSEMENTS";

-- CreateTable
CREATE TABLE "file_backup" (
    "id" TEXT,
    "filename" TEXT,
    "originalName" TEXT,
    "mimetype" TEXT,
    "path" TEXT,
    "size" INTEGER,
    "thumbnailUrl" TEXT,
    "createdAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3)
);

-- CreateTable
CREATE TABLE "_AIRBRUSHING_INVOICES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_AIRBRUSHING_INVOICES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_AIRBRUSHING_INVOICE_REIMBURSEMENTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_AIRBRUSHING_INVOICE_REIMBURSEMENTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_INVOICES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_INVOICES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_INVOICE_REIMBURSEMENTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_INVOICE_REIMBURSEMENTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_INVOICES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_INVOICES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_INVOICE_REIMBURSEMENTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_INVOICE_REIMBURSEMENTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_INVOICES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE INDEX "_AIRBRUSHING_INVOICES_B_index" ON "_AIRBRUSHING_INVOICES"("B");

-- CreateIndex
CREATE INDEX "_AIRBRUSHING_INVOICE_REIMBURSEMENTS_B_index" ON "_AIRBRUSHING_INVOICE_REIMBURSEMENTS"("B");

-- CreateIndex
CREATE INDEX "_ORDER_INVOICES_B_index" ON "_ORDER_INVOICES"("B");

-- CreateIndex
CREATE INDEX "_ORDER_INVOICE_REIMBURSEMENTS_B_index" ON "_ORDER_INVOICE_REIMBURSEMENTS"("B");

-- CreateIndex
CREATE INDEX "_TASK_INVOICES_B_index" ON "_TASK_INVOICES"("B");

-- CreateIndex
CREATE INDEX "_TASK_INVOICE_REIMBURSEMENTS_B_index" ON "_TASK_INVOICE_REIMBURSEMENTS"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_INVOICES_B_index" ON "_EXTERNAL_WITHDRAWAL_INVOICES"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS_B_index" ON "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS"("B");

-- CreateIndex
CREATE INDEX "Paint_colorOrder_idx" ON "Paint"("colorOrder");

-- CreateIndex
CREATE INDEX "Truck_garageId_idx" ON "Truck"("garageId");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_avatarId_fkey" FOREIGN KEY ("avatarId") REFERENCES "File"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_INVOICES" ADD CONSTRAINT "_AIRBRUSHING_INVOICES_A_fkey" FOREIGN KEY ("A") REFERENCES "Airbrushing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_INVOICES" ADD CONSTRAINT "_AIRBRUSHING_INVOICES_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_AIRBRUSHING_INVOICE_REIMBURSEMENTS_A_fkey" FOREIGN KEY ("A") REFERENCES "Airbrushing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_AIRBRUSHING_INVOICE_REIMBURSEMENTS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_INVOICES" ADD CONSTRAINT "_ORDER_INVOICES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_INVOICES" ADD CONSTRAINT "_ORDER_INVOICES_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_ORDER_INVOICE_REIMBURSEMENTS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_ORDER_INVOICE_REIMBURSEMENTS_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_INVOICES" ADD CONSTRAINT "_TASK_INVOICES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_INVOICES" ADD CONSTRAINT "_TASK_INVOICES_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_TASK_INVOICE_REIMBURSEMENTS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_TASK_INVOICE_REIMBURSEMENTS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_INVOICES" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICES_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_INVOICES" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICES_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_INVOICE_REIMBURSEMENTS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;
