-- Rename TRUCK_SPOT enum values from old format (B#_A#) to new format (B#_F#_V#)
-- Where F = Faixa (lane), V = Vaga (spot)

-- Barracão 1 (B1)
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_A1' TO 'B1_F1_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_A2' TO 'B1_F1_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_A3' TO 'B1_F1_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_B1' TO 'B1_F2_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_B2' TO 'B1_F2_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_B3' TO 'B1_F2_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_C1' TO 'B1_F3_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_C2' TO 'B1_F3_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B1_C3' TO 'B1_F3_V3';

-- Barracão 2 (B2)
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_A1' TO 'B2_F1_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_A2' TO 'B2_F1_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_A3' TO 'B2_F1_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_B1' TO 'B2_F2_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_B2' TO 'B2_F2_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_B3' TO 'B2_F2_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_C1' TO 'B2_F3_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_C2' TO 'B2_F3_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B2_C3' TO 'B2_F3_V3';

-- Barracão 3 (B3)
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_A1' TO 'B3_F1_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_A2' TO 'B3_F1_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_A3' TO 'B3_F1_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_B1' TO 'B3_F2_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_B2' TO 'B3_F2_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_B3' TO 'B3_F2_V3';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_C1' TO 'B3_F3_V1';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_C2' TO 'B3_F3_V2';
ALTER TYPE "TRUCK_SPOT" RENAME VALUE 'B3_C3' TO 'B3_F3_V3';

-- PATIO remains unchanged
