/*
  Warnings:

  - You are about to drop the column `nfeId` on the `ExternalWithdrawal` table. All the data in the column will be lost.
  - You are about to drop the column `receiptId` on the `ExternalWithdrawal` table. All the data in the column will be lost.
  - You are about to drop the column `budgetId` on the `Order` table. All the data in the column will be lost.
  - You are about to drop the column `nfeId` on the `Order` table. All the data in the column will be lost.
  - You are about to drop the column `receiptId` on the `Order` table. All the data in the column will be lost.
  - You are about to drop the column `budgetId` on the `Task` table. All the data in the column will be lost.
  - You are about to drop the column `nfeId` on the `Task` table. All the data in the column will be lost.
  - You are about to drop the column `receiptId` on the `Task` table. All the data in the column will be lost.
  - Made the column `app_id` on table `deployments` required. This step will fail if there are existing NULL values in that column.
  - Made the column `git_commit_id` on table `deployments` required. This step will fail if there are existing NULL values in that column.

*/
-- AlterEnum
ALTER TYPE "ChangeLogEntityType" ADD VALUE 'DEPLOYMENT';

-- DropForeignKey
ALTER TABLE "public"."ExternalWithdrawal" DROP CONSTRAINT "ExternalWithdrawal_nfeId_fkey";

-- DropForeignKey
ALTER TABLE "public"."ExternalWithdrawal" DROP CONSTRAINT "ExternalWithdrawal_receiptId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Order" DROP CONSTRAINT "Order_budgetId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Order" DROP CONSTRAINT "Order_nfeId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Order" DROP CONSTRAINT "Order_receiptId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Task" DROP CONSTRAINT "Task_budgetId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Task" DROP CONSTRAINT "Task_nfeId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Task" DROP CONSTRAINT "Task_receiptId_fkey";

-- DropIndex
DROP INDEX "public"."deployments_environment_status_idx";

-- AlterTable
ALTER TABLE "ExternalWithdrawal" DROP COLUMN "nfeId",
DROP COLUMN "receiptId";

-- AlterTable
ALTER TABLE "Order" DROP COLUMN "budgetId",
DROP COLUMN "nfeId",
DROP COLUMN "receiptId";

-- AlterTable
ALTER TABLE "Task" DROP COLUMN "budgetId",
DROP COLUMN "nfeId",
DROP COLUMN "receiptId";

-- AlterTable
ALTER TABLE "deployments" ALTER COLUMN "status_order" SET DEFAULT 2,
ALTER COLUMN "app_id" SET NOT NULL,
ALTER COLUMN "git_commit_id" SET NOT NULL;

-- CreateTable
CREATE TABLE "_AIRBRUSHING_BUDGETS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_AIRBRUSHING_BUDGETS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_AIRBRUSHING_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_AIRBRUSHING_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_AIRBRUSHING_NFE_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_BUDGETS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_BUDGETS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_NFES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_NFES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_RECEIPTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_RECEIPTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_ORDER_NFE_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_ORDER_NFE_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_BUDGETS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_BUDGETS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_NFES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_NFES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_RECEIPTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_RECEIPTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_TASK_NFE_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TASK_NFE_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_NFES" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFES_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_RECEIPTS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_RECEIPTS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE INDEX "_AIRBRUSHING_BUDGETS_B_index" ON "_AIRBRUSHING_BUDGETS"("B");

-- CreateIndex
CREATE INDEX "_AIRBRUSHING_REEMBOLSOS_B_index" ON "_AIRBRUSHING_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_AIRBRUSHING_NFE_REEMBOLSOS_B_index" ON "_AIRBRUSHING_NFE_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_ORDER_BUDGETS_B_index" ON "_ORDER_BUDGETS"("B");

-- CreateIndex
CREATE INDEX "_ORDER_NFES_B_index" ON "_ORDER_NFES"("B");

-- CreateIndex
CREATE INDEX "_ORDER_RECEIPTS_B_index" ON "_ORDER_RECEIPTS"("B");

-- CreateIndex
CREATE INDEX "_ORDER_REEMBOLSOS_B_index" ON "_ORDER_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_ORDER_NFE_REEMBOLSOS_B_index" ON "_ORDER_NFE_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_TASK_BUDGETS_B_index" ON "_TASK_BUDGETS"("B");

-- CreateIndex
CREATE INDEX "_TASK_NFES_B_index" ON "_TASK_NFES"("B");

-- CreateIndex
CREATE INDEX "_TASK_RECEIPTS_B_index" ON "_TASK_RECEIPTS"("B");

-- CreateIndex
CREATE INDEX "_TASK_REEMBOLSOS_B_index" ON "_TASK_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_TASK_NFE_REEMBOLSOS_B_index" ON "_TASK_NFE_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_NFES_B_index" ON "_EXTERNAL_WITHDRAWAL_NFES"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_RECEIPTS_B_index" ON "_EXTERNAL_WITHDRAWAL_RECEIPTS"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_B_index" ON "_EXTERNAL_WITHDRAWAL_REEMBOLSOS"("B");

-- CreateIndex
CREATE INDEX "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_B_index" ON "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS"("B");

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_BUDGETS" ADD CONSTRAINT "_AIRBRUSHING_BUDGETS_A_fkey" FOREIGN KEY ("A") REFERENCES "Airbrushing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_BUDGETS" ADD CONSTRAINT "_AIRBRUSHING_BUDGETS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_REEMBOLSOS" ADD CONSTRAINT "_AIRBRUSHING_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "Airbrushing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_REEMBOLSOS" ADD CONSTRAINT "_AIRBRUSHING_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_NFE_REEMBOLSOS" ADD CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "Airbrushing"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_AIRBRUSHING_NFE_REEMBOLSOS" ADD CONSTRAINT "_AIRBRUSHING_NFE_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_BUDGETS" ADD CONSTRAINT "_ORDER_BUDGETS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_BUDGETS" ADD CONSTRAINT "_ORDER_BUDGETS_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_NFES" ADD CONSTRAINT "_ORDER_NFES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_NFES" ADD CONSTRAINT "_ORDER_NFES_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_RECEIPTS" ADD CONSTRAINT "_ORDER_RECEIPTS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_RECEIPTS" ADD CONSTRAINT "_ORDER_RECEIPTS_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_REEMBOLSOS" ADD CONSTRAINT "_ORDER_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_REEMBOLSOS" ADD CONSTRAINT "_ORDER_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_NFE_REEMBOLSOS" ADD CONSTRAINT "_ORDER_NFE_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ORDER_NFE_REEMBOLSOS" ADD CONSTRAINT "_ORDER_NFE_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_BUDGETS" ADD CONSTRAINT "_TASK_BUDGETS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_BUDGETS" ADD CONSTRAINT "_TASK_BUDGETS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_NFES" ADD CONSTRAINT "_TASK_NFES_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_NFES" ADD CONSTRAINT "_TASK_NFES_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_RECEIPTS" ADD CONSTRAINT "_TASK_RECEIPTS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_RECEIPTS" ADD CONSTRAINT "_TASK_RECEIPTS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_REEMBOLSOS" ADD CONSTRAINT "_TASK_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_REEMBOLSOS" ADD CONSTRAINT "_TASK_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_NFE_REEMBOLSOS" ADD CONSTRAINT "_TASK_NFE_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TASK_NFE_REEMBOLSOS" ADD CONSTRAINT "_TASK_NFE_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFES" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFES_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFES" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFES_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_RECEIPTS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_RECEIPTS_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_RECEIPTS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_RECEIPTS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_REEMBOLSOS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_REEMBOLSOS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_A_fkey" FOREIGN KEY ("A") REFERENCES "ExternalWithdrawal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS" ADD CONSTRAINT "_EXTERNAL_WITHDRAWAL_NFE_REEMBOLSOS_B_fkey" FOREIGN KEY ("B") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;
